### ISSUE TITLE
Middleware Performance Question

### ISSUE THREAD

**Issue by wesleykendall** [carta/postgres_audit_triggers#1]
Apologies if there's a better place to put this! First of all, wonderful app! I was evaluating the approach in this app for creating a temporary table with metadata for the request. Out of curiosity, did you explore setting postgres variables like https://github.com/torstenrudolf/django-audit-trigger/blob/master/audit/middleware.py#L51 does? Or was that not flexible enough?

In your experience, are there are performance implications of creating a temp table for every request in the middleware? Or have you noticed any substantial difference?

Thanks for your help. We're evaluating a couple approaches for auditing postgres at the moment, and we like this library the best so far

**Comment by jaredhobbs** [comment]
Sorry, just saw this comment! I hadn't looked at setting Postgres variables like that but it seems like it would accomplish part of what we needed. We needed to be flexible enough to add arbitrary metadata to the audit table which is why we went with the temp table approach. We haven't noticed any performance hits from the temp table although there _is_ a performance hit just from writing to the audit table on every insert/update/delete but there really isn't anyway around that.

**Comment by wesleykendall** [comment]
Thanks for the response!

**Comment by wesleykendall** [comment]
@jaredhobbs I thought I'd follow up here with an approach that I ended up using for a history tracking library I just open sourced (https://django-pghistory.readthedocs.io/en/latest/) in case you are interested in using the same approach for this library. This approach allows for tracking free-form metadata without any additional queries to the database.

django-pghistory has a ``pghistory.context()`` context manager that allows you to add free-form metadata to an event that's tracked in the database - see https://github.com/jyveapp/django-pghistory/blob/master/pghistory/tracking.py#L103 for reference

What this does is the following:

1. Adds a "pre_execute" hook to the database cursor using https://github.com/jyveapp/django-pgconnection, which is the library you could use to do a similar approach. Pre-execute hooks are functions that are executed before every SQL statement in Django, and they can return modified SQL to be executed.
2. The pre-execute hook used by django-pghistory returns a modified SQL that prepends two "SET" operations to the SQL. It sets a UUID and a serialized JSON variable of free-form metadata that is generated by the app using ``pghistory.context()``.
3. Again, this is not doing any additional database calls, but rather modifying whatever SQL is already being issued by the application. It does increase the SQL payload, but there are no additional database write hits or anything like that.
4. The audit triggers themselves, which are installed by the django-pghistory app, load the variable as a JSON variable in a way like so - https://github.com/jyveapp/django-pghistory/blob/master/pghistory/models.py#L41.

The nice thing about this approach is that you can call `pghistory.context` anywhere in your application to attach additional context to audit events that happen. You can also instrument manage.py or tasks to attach context if they don't go through the request/response cycle (shown in the docs for pghistory)

Anyways, I just thought I would let you know about this approach in case you want something that is more optimized and possibly more flexible. I've been using this library in a very large and complex Django app with lots of traffic. Maybe not the same size and complexity as Carta's though :)
